### ISSUE TITLE
empty string as default version breaks expiry validation

### ISSUE THREAD

**Issue by ljosberinn** [i18next/i18next-localstorage-backend#18]
Hi,

noticed that my geti18n endpoint receives requests although its data is definitely already stored. Providing `defaultVersion: anyString` fixed it.

https://github.com/i18next/i18next-localstorage-backend/blob/master/src/index.js#L33
ensures the default version is an empty string

https://github.com/i18next/i18next-localstorage-backend/blob/master/src/index.js#L85
falls back to the defaultValue if none was provided for the current language
right after, it checks whether a version was found and _only then_ sets it - `''` is falsy though, so the value won't get set

https://github.com/i18next/i18next-localstorage-backend/blob/master/src/index.js#L69
which leads to this always being false, leading to a permanent refetch

proposed solutions:
- unconditionally set version in `save`: `data.i18nVersion = this.getVersion(language);` - would lead to an unecessary key in localStorage though
- more validation logic against `this.options.defaultVersion` in `read`

Both sound kinda stupid to me right now, but that's because I've been debugging this for an hour and now its past 4 am. :sweat_smile: I can create a PR later.

**Comment by jamuhl** [comment]
👍PR welcome....@slevy85 you might also look into this?

**Comment by slevy85** [comment]
I am sorry for this I introduced a regression, the problem is `version === local.i18nVersion` compares empty string with undefined, with double equals it would workd but a better solution is to intialize defaultVersion to undefined.
