### ISSUE TITLE
Provide support for indexedDB and localforage

### ISSUE THREAD

**Issue by ahmedosama5200** [i18next/i18next-localstorage-backend#26]
## 🚀 Feature Proposal

Add support for indexedDB and localforage library in addition to localstorage

## Motivation

Right now, You could only store permanent translation cache in `local storage` which has some known issues e.g. It's synchronous blocking the UI, this could be problematic if the file has so many translation keys. `IndexedDB` is much better. Also, you could go further and support `localforage` library which wraps all of these technologies and fallbacks to `local storage` if the user browser doesn't support them

**Comment by jamuhl** [comment]
We won't provide every implementation - that is the job of the community. Creating a "backend" plugin like the localStorage is very simple. Give it a try and share it with the community: https://www.i18next.com/misc/creating-own-plugins#backend
