### ISSUE TITLE
Locize requests are submitted after caching.

### ISSUE THREAD

**Issue by iamskok** [i18next/i18next-localstorage-backend#34]
## 🐛 Bug Report

After caching results subsequent requests are submitted to locize service on page refresh.

![Screen Shot 2021-09-02 at 1 50 13 PM](https://user-images.githubusercontent.com/5145359/131897017-9c0130ad-9386-4e1d-a69b-18c5414388de.png)
![Screen Shot 2021-09-02 at 1 49 30 PM](https://user-images.githubusercontent.com/5145359/131897041-0643f98b-21e5-4b77-b183-946b79c67cfa.png)

## To Reproduce

[GitHub repo](https://github.com/iamskok/react-i18next-localize-test)

## Expected behavior

No subsequent requests to locize after caching.

## Your Environment

- *runtime version*:
  - node v14.17.5
  - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- *module version*:
  - "i18next-locize-backend": "^4.2.3",
- *os*: Mac

**Comment by adrai** [comment]
Please check if this is still the case after you change the load option here: https://github.com/locize/i18next-locize-backend/issues/342#issuecomment-911951258

**Comment by iamskok** [comment]
Fixed by adding `load: 'currentOnly'` option.
