### ISSUE TITLE
Typescript types 

### ISSUE THREAD

**Issue by VincentLanglet** [i18next/i18next-localstorage-backend#4]
Kinda related to https://github.com/i18next/i18next-xhr-backend/issues/295

If I want to add typescript type. Should I prefer DefinitivelyTyped or here ?

**Comment by jamuhl** [comment]
Feel free to provide a PR

**Comment by VincentLanglet** [comment]
@jamuhl Done : https://github.com/i18next/i18next-localstorage-backend/pull/5
