### ISSUE TITLE
Cache fallback values in the users language

### ISSUE THREAD

**Issue by rschluesselbauer** [i18next/i18next-localstorage-backend#40]
## 🚀 Feature Proposal
Add option to cache translations of the fallback language for the originally requested language.

## Motivation
If translations for a language do not exist and the fallback language is used, it would make sense to cache that result for the requested language to avoid multiple requests that always result in a 404.

If translations in the requested language do not exist, we make a bunch of 404 requests with the HTTP backend.
Then the fallback language is used and the translations are cached for the fallback language. 
If the user reloads the page, they have to go through the 404 requests again before falling back to the cache.
This could be avoided 

## Example
Imagine a setup with a localstorage-backend before a http-backend:
* A user with language DE visits the site
* DE translations are not available in localstorage
* Requests are made to the http-backend returning 404
* The fallback language is used

Whenever the page is reloaded the 404ing requests would be repeated.

**Comment by adrai** [comment]
why not simply define supportedLngs and prevent all 404?

**Comment by rschluesselbauer** [comment]
That is a good point.
However, in my case an admin can upload translation files in any language, therefore I do not know 
* which languages are supported at the moment (can be solved by adding an endpoint returning supported lanugages)
* if there exists a translation for all namespaces

If I want to allow partial translation (translating only some namespaces), then this does not work.

**Comment by adrai** [comment]
Then you may need to create your own chained-backend logic.

**Comment by rschluesselbauer** [comment]
Ok if this doesn't make any sense in the context of this cache, I'll close the issue.
Thank you for your feedback!
