### ISSUE TITLE
Translations are not set to localStorage

### ISSUE THREAD

**Issue by omarawad0** [i18next/i18next-localstorage-backend#48]
Why my translations are not set automatically to the locaStorage. am I missing something?
BTW, i tried to call it manually with `i18next.services.backendConnector.backend.backends[0].save('en', [ns], { translation })` and i am able to see it on LocalStorage.

Also, how can I validate that subsequent requests for the same translations will be served directly from the local storage cache?

Here is my config

```js
i18n
  .use(LanguageDetector)
  .use(LocalStorageBackend)
  .use(initReactI18next)
  .init({
    debug: true, // Set this to true to see logs in the console
    fallbackLng: "en",
    resources: {
      en: {
        translation: {
          greeting: "Hello, World!",
          language: "English",
        },
      },
      ar: {
        translation: {
          greeting: "مرحبًا بالعالم!",
          language: "العربية",
        },
      },
    },
    backend: {
      backends: [LocalStorageBackend],
      backendOptions: [
        {
          expirationTime: 7 * 24 * 60 * 60 * 1000, // 7 days
          versions: {
            en: "v1.0.0",
            ar: "v1.0.0",
          },
        },
      ],
    },
  });

```

## Your Environment

- *i18next version*: i.e. 21.6.16
- *os*: Mac

**Comment by adrai** [comment]
You need to setup your i18next config correctly with the chained backed, like here: https://www.i18next.com/how-to/caching

**Comment by adrai** [comment]
and it will not work with in-memory translation resources.
It would not make sense without a remote backend.
